### ISSUE TITLE
lock item issue on postgres

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#101]
Hi,

Trying the recent lock record feature.
Currently getting the following error on postgresql 11

`While creating an item the following error was raised: Error while creating table: zero-length delimited identifier at or near """" LINE 1: CREATE SEQUENCE "" ^
`

**Comment by jam-py** [comment]
Hi, Davide 
Can you send me more detailed logs.

**Comment by ddavidebor** [comment]
@jam-py of course here they are:
```

7.0.0.1 - - [25/Apr/2019 20:45:48] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2019 20:45:48] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2019 20:45:49] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2019 20:45:49] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2019 20:45:50] "POST /api HTTP/1.1" 200 -
CREATE SEQUENCE ""
CREATE TABLE "fermiumlabs_locks"
(
"id" INTEGER PRIMARY KEY DEFAULT NEXTVAL('""'),
"item_id" INTEGER,
"item_rec_id" INTEGER,
"version" INTEGER)

ALTER SEQUENCE "" OWNED BY "fermiumlabs_locks"."id"

Error: zero-length delimited identifier at or near """"
LINE 1: CREATE SEQUENCE ""
                        ^

 command: CREATE SEQUENCE ""
 params: None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/jam/execute.py", line 162, in execute_sql_connection
    result = execute_list(cursor, db_module, command, delta_result, params, select, ddl, messages)
  File "/usr/local/lib/python2.7/site-packages/jam/execute.py", line 135, in execute_list
    res = execute_command(cursor, db_module, com, params, select, ddl, messages)
  File "/usr/local/lib/python2.7/site-packages/jam/execute.py", line 65, in execute_command
    result = execute(cursor, command, params)
  File "/usr/local/lib/python2.7/site-packages/jam/execute.py", line 30, in execute
    cursor.execute(command)
ProgrammingError: zero-length delimited identifier at or near """"
LINE 1: CREATE SEQUENCE ""
                        ^

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/jam/adm_server.py", line 2519, in create_system_item
    items.apply(params={'manual_update': False})
  File "/usr/local/lib/python2.7/site-packages/jam/dataset.py", line 2088, in apply
    self.do_apply(params, safe, connection)
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 118, in do_apply
    data, error = self.apply_changes((changes, params), safe, connection)
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 260, in apply_changes
    result = self.on_apply(self, delta, params)
  File "/usr/local/lib/python2.7/site-packages/jam/adm_server.py", line 2849, in items_apply_changes
    result = items_execute_insert(item, delta, manual_update)
  File "/usr/local/lib/python2.7/site-packages/jam/adm_server.py", line 2774, in items_execute_insert
    raise Exception(item.task.language('error_creating_table') % (error))
Exception: Error while creating table: zero-length delimited identifier at or near """"
LINE 1: CREATE SEQUENCE ""
                        ^

127.0.0.1 - - [25/Apr/2019 20:45:51] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2019 20:45:54] "GET /builder.html HTTP/1.1" 304 -
127.0.0.1 - - [25/Apr/2019 20:45:54] "GET /jam/css/bootstrap-modal.css HTTP/1.1" 304 -
127.0.0.1 - - [25/Apr/2019 20:45:54] "GET /jam/css/bootstrap-cerulean.css HTTP/1.1" 304 -
127.0.0.1 - - [25/Apr/2019 20:45:54] "GET /jam/css/bootstrap-responsive.css HTTP/1.1" 304 -
127.0.0.1 - - [25/Apr/2019 20:45:54] "GET /jam/css/datepicker.css HTTP/1.1" 304 -
127.0.0.1 - - [25/Apr/2019 20:45:54] "GET /jam/css/jam12.css HTTP/1.1" 304 -
```

**Comment by jam-py** [comment]
Thank you Davide, I fixed the bug
