### ISSUE TITLE
jampy not accepting postgresql not accepting host

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#106]
Hello,

I am moving postgresql out of localhost, but it seems that jam-py is always using localhost even if i set a different host in the database configuration.

```
127.0.0.1 - - [15/Jul/2019 17:57:15] "GET /jam/img/glyphicons-halflings.png HTTP/1.1" 304 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/jam/wsgi.py", line 456, in on_api
    data = self.get_response(item, method, params)
  File "/usr/local/lib/python2.7/site-packages/jam/wsgi.py", line 481, in get_response
    return item.select_records(params, safe=True)
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 219, in select_records
    result = self.execute_open(params)
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 195, in execute_open
    rows = self.task.select(sqls[0], connection, db_module)
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 965, in select
    result, error = self.execute(command, None, connection, db_module, select=True)
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 959, in execute
    result = self.pool_execute(command, params, select)
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 936, in pool_execute
    con = self.connect()
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 906, in connect
    return self.pool.connect()
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/pool/base.py", line 354, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/pool/base.py", line 751, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/pool/base.py", line 483, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/pool/impl.py", line 138, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/pool/impl.py", line 135, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/pool/base.py", line 299, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/pool/base.py", line 428, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/pool/base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/site-packages/jam/third_party/sqlalchemy/pool/base.py", line 255, in <lambda>
    return lambda crec: creator()
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 903, in getconn
    return self.create_connection()
  File "/usr/local/lib/python2.7/site-packages/jam/server_classes.py", line 896, in create_connection
    self.db_password, self.db_host, self.db_port, self.db_encoding, self.db_server)
  File "/usr/local/lib/python2.7/site-packages/jam/db/postgres.py", line 40, in connect
    return psycopg2.connect(dbname=database, user=user, password=password, host=host, port=port)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

127.0.0.1 - - [15/Jul/2019 17:57:15] "POST /api HTTP/1.1" 200 - 
```

![download](https://user-images.githubusercontent.com/9055742/61230707-dbd2c880-a72a-11e9-9c8b-a02e717876f8.png)

**Comment by ddavidebor** [comment]
I'm an idiot, a simple restart of the app will solve...
