### ISSUE TITLE
RedHat 8 issue

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#139]
RedHat 8.1

Installed by "pip3 install jam.py"
Switched to Python3 by: "alternatives --config python"

Copied demo to /var/www/html

Created jam.conf:

```
<VirtualHost *:80>

    ServerName jam.research...
    ServerAlias jam.research...
    DocumentRoot /var/www/html/

    WSGIDaemonProcess  assets3 user=apache group=apache processes=1 threads=5
    WSGIScriptAlias / /var/www/html/wsgi.py
        <Directory /var/www/html/>

        Options +ExecCGI 
        SetHandler wsgi-script
        AddHandler wsgi-script .py

        Order deny,allow
        Allow from all
        Require all granted
        <Files wsgi.py>
            Order deny,allow
            Allow from all

            # comment the following for ubuntu <13
            Require all granted
        </Files>

    </Directory>

    <Directory /var/www/html/static>

        # comment the following for ubuntu < 13
        Require all granted

    </Directory>
</VirtualHost>
```

Tried to enable Safe Mode, but:

```
[Wed Feb 05 13:54:17.731377 2020] [mpm_event:notice] [pid 31192:tid 140563092703488] AH00489: Apache/2.4.37 (Red Hat Enterprise Linux) mod_wsgi/4.6.4 Python/3.6 configured -- resuming normal operations
[Wed Feb 05 13:54:17.731396 2020] [core:notice] [pid 31192:tid 140563092703488] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Feb 05 13:54:20.698217 2020] [wsgi:error] [pid 31199:tid 140562478053120] [client ...:38566] /usr/local/lib/python3.6/site-packages/jam/third_party/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
[Wed Feb 05 13:54:20.698262 2020] [wsgi:error] [pid 31199:tid 140562478053120] [client ...:38566]   BrokenFilesystemWarning,
[Wed Feb 05 13:54:21.623547 2020] [wsgi:error] [pid 31419:tid 140562478053120] [client ...:38570] /usr/local/lib/python3.6/site-packages/jam/third_party/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii', referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:21.623577 2020] [wsgi:error] [pid 31419:tid 140562478053120] [client ...:38570]   BrokenFilesystemWarning,, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:21.656385 2020] [wsgi:error] [pid 31198:tid 140562486445824] [client ...:38576] /usr/local/lib/python3.6/site-packages/jam/third_party/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii', referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:21.656478 2020] [wsgi:error] [pid 31198:tid 140562486445824] [client ...:38576]   BrokenFilesystemWarning,, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944784 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] ERROR - attempt to write a readonly database, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944813 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] Traceback (most recent call last):, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944816 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]   File "/usr/local/lib/python3.6/site-packages/jam/server_classes.py", line 246, in apply_changes, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944819 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]     result = self.on_apply(self, delta, params, connection), referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944822 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] TypeError: do_on_apply_param_changes() takes 3 positional arguments but 4 were given, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944825 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] , referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944827 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] During handling of the above exception, another exception occurred:, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944829 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] , referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944837 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] Traceback (most recent call last):, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944840 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]   File "/usr/local/lib/python3.6/site-packages/jam/execute.py", line 28, in execute, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944842 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]     cursor.execute(command, params), referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944846 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] sqlite3.OperationalError: attempt to write a readonly database, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944851 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] , referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944956 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] Traceback (most recent call last):, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944969 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]   File "/usr/local/lib/python3.6/site-packages/jam/server_classes.py", line 246, in apply_changes, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944972 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]     result = self.on_apply(self, delta, params, connection), referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944981 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] TypeError: do_on_apply_param_changes() takes 3 positional arguments but 4 were given, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944987 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] , referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944990 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] During handling of the above exception, another exception occurred:, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944992 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] , referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.944996 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] Traceback (most recent call last):, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.945010 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]   File "/usr/local/lib/python3.6/site-packages/jam/execute.py", line 133, in execute_sql_connection, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.945013 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]     res = execute_delta(cursor, db_module, command, params, delta_result), referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.945018 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]   File "/usr/local/lib/python3.6/site-packages/jam/execute.py", line 102, in execute_delta, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.945020 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]     process_delta(cursor, db_module, delta, None, delta_result), referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.945025 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]   File "/usr/local/lib/python3.6/site-packages/jam/execute.py", line 79, in process_delta, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.945027 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]     execute(cursor, command, params), referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.945036 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]   File "/usr/local/lib/python3.6/site-packages/jam/execute.py", line 28, in execute, referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.945039 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580]     cursor.execute(command, params), referer: http://jam.research..../builder.html
[Wed Feb 05 13:54:34.945047 2020] [wsgi:error] [pid 31198:tid 140561327585024] [client ...:38580] sqlite3.OperationalError: attempt to write a readonly database, referer: http://jam.research..../builder.html
```

Folder privileges:

```
[root@is-nix-test241 html]# ls -latr
total 1568
drwxr-xr-x. 4 root   root        33 Feb  5 13:10 ..
drwxr-xr-x. 2 apache apache      25 Feb  5 13:12 css
-rw-r--r--. 1 apache apache 1340416 Feb  5 13:12 demo.sqlite
-rw-r--r--. 1 apache apache   10165 Feb  5 13:12 index.html
drwxr-xr-x. 2 apache apache      67 Feb  5 13:12 reports
-rwxr-xr-x. 1 apache apache     199 Feb  5 13:12 server.py
drwxr-xr-x. 6 apache apache      56 Feb  5 13:12 static
-rw-r--r--. 1 apache apache       0 Feb  5 13:12 t
-rw-r--r--. 1 apache apache      85 Feb  5 13:12 wsgi.py
-rw-r--r--. 1 root   root       290 Feb  5 13:17 .htaccess
-rw-rw-rw-. 1 apache apache  133120 Feb  5 13:29 langs.sqlite
-rw-r--r--. 1 apache apache   99328 Feb  5 13:29 admin.sqlite
drwxr-xr-x. 7 root   root       204 Feb  5 13:29 .
drwxr-xr-x. 2 apache apache      21 Feb  5 13:30 js
drwxr-xr-x. 2 apache apache     130 Feb  5 13:54 locks
```
This problem rings a bell, but do not remember how it was solved before.

**Comment by platipusica** [comment]
Hmm:

```
[Wed Feb 05 15:02:33.876559 2020] [mpm_event:notice] [pid 4679:tid 139687622519040] AH00489: Apache/2.4.37 (Red Hat Enterprise Linux) mod_wsgi/4.6.4 Python/3.6 configured -- resuming normal operations
[Wed Feb 05 15:02:33.876580 2020] [core:notice] [pid 4679:tid 139687622519040] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'




[Wed Feb 05 15:02:40.828361 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128] mod_wsgi (pid=4685): Failed to exec Python script file '/var/www/html/wsgi.py'.
[Wed Feb 05 15:02:40.828412 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128] mod_wsgi (pid=4685): Exception occurred processing WSGI script '/var/www/html/wsgi.py'.
[Wed Feb 05 15:02:40.828908 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128] Traceback (most recent call last):
[Wed Feb 05 15:02:40.828940 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]   File "/var/www/html/wsgi.py", line 4, in <module>
[Wed Feb 05 15:02:40.828944 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]     application = create_application(__file__)
[Wed Feb 05 15:02:40.828948 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/wsgi.py", line 79, in create_application
[Wed Feb 05 15:02:40.828951 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]     application = App(work_dir, load_task)
[Wed Feb 05 15:02:40.828956 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/wsgi.py", line 152, in __init__
[Wed Feb 05 15:02:40.828958 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]     create_admin(self)
[Wed Feb 05 15:02:40.828962 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/admin/admin.py", line 54, in create_admin
[Wed Feb 05 15:02:40.828965 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]     init_admin(task)
[Wed Feb 05 15:02:40.828969 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/admin/admin.py", line 37, in init_admin
[Wed Feb 05 15:02:40.828972 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]     langs.update_langs(task)
[Wed Feb 05 15:02:40.828976 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/langs.py", line 101, in update_langs
[Wed Feb 05 15:02:40.828978 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128]     cursor.execute(sql, (field_values))
[Wed Feb 05 15:02:40.828989 2020] [wsgi:error] [pid 4685:tid 139687016261376] [client ...:41128] sqlite3.OperationalError: attempt to write a readonly database
```


I even tried this:

```
(py36) [root@is-nix-test241 html]# cat wsgi.py
import os
import sys
path = '/var/www/html'
if path not in sys.path:
    sys.path.append(path)
from jam.wsgi import create_application
application = create_application(path)
```

Not working on RedHat 8.1

**Comment by jam-py** [comment]
Hello,

It seems that admin.sqlite is read only.

Regards

ср, 5 февр. 2020 г. в 10:09, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
:)

It's not that:

```
[Wed Feb 05 15:34:34.294898 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912] mod_wsgi (pid=5897): Failed to exec Python script file '/var/www/html/wsgi.py'.
[Wed Feb 05 15:34:34.294961 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912] mod_wsgi (pid=5897): Exception occurred processing WSGI script '/var/www/html/wsgi.py'.
[Wed Feb 05 15:34:34.295467 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912] Traceback (most recent call last):
[Wed Feb 05 15:34:34.295500 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]   File "/var/www/html/wsgi.py", line 7, in <module>
[Wed Feb 05 15:34:34.295504 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]     application = create_application(path)
[Wed Feb 05 15:34:34.295509 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/wsgi.py", line 79, in create_application
[Wed Feb 05 15:34:34.295511 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]     application = App(work_dir, load_task)
[Wed Feb 05 15:34:34.295516 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/wsgi.py", line 152, in __init__
[Wed Feb 05 15:34:34.295518 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]     create_admin(self)
[Wed Feb 05 15:34:34.295522 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/admin/admin.py", line 54, in create_admin
[Wed Feb 05 15:34:34.295525 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]     init_admin(task)
[Wed Feb 05 15:34:34.295529 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/admin/admin.py", line 37, in init_admin
[Wed Feb 05 15:34:34.295531 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]     langs.update_langs(task)
[Wed Feb 05 15:34:34.295535 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/langs.py", line 101, in update_langs
[Wed Feb 05 15:34:34.295541 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912]     cursor.execute(sql, (field_values))
[Wed Feb 05 15:34:34.295552 2020] [wsgi:error] [pid 5897:tid 140336848434944] [client 130.95.255.66:41912] sqlite3.OperationalError: attempt to write a readonly database
```

**Comment by platipusica** [comment]
I think this is RedHat issue, leave it with me...

**Comment by platipusica** [comment]
Hmm, 

jam-project is not creating langs, locks etc? Because if it is not creating this, the Apache will not be able to create it, and on first start with empty project it will fail!

But than, even if I run ./server locally to create this files, the Apache will not be able to continue b/c read only db:

![Screenshot from 2020-02-05 16-03-49](https://user-images.githubusercontent.com/9026100/73822605-6bf46e80-4831-11ea-99ca-c1941a95fc77.png)

I can  raise this issue with RedHat, but not creating all files for Apache is an deployment issue.

D.

**Comment by jam-py** [comment]
It seems to me that it is related to access rights

sqlite3.OperationalError: attempt to write a readonly database



ср, 5 февр. 2020 г. в 11:09, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
```
Wed Feb 05 16:22:22.864006 2020] [wsgi:error] [pid 2025:tid 140097177470720] [client ...:43068]   File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/server_classes.py", line 246, in apply_changes, referer: http://jam.research..../builder.html
[Wed Feb 05 16:22:22.864008 2020] [wsgi:error] [pid 2025:tid 140097177470720] [client ...:43068]     result = self.on_apply(self, delta, params, connection), referer: http://jam.research..../builder.html
[Wed Feb 05 16:22:22.864011 2020] [wsgi:error] [pid 2025:tid 140097177470720] [client ...:43068] TypeError: do_on_apply_param_changes() takes 3 positional arguments but 4 were given, referer: http://jam.research..../builder.html
```
