### ISSUE TITLE
ValueError: Circular reference detected

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#172]
Hi, 

imported sqlite3 table, set the rest and got:

```
Traceback (most recent call last):
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/third_party/werkzeug/local.py", line 230, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/third_party/werkzeug/middleware/shared_data.py", line 260, in __call__
    return self.app(environ, start_response)
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/wsgi.py", line 212, in __call__
    response = getattr(self, 'on_' + endpoint)(request, **values)
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/wsgi.py", line 616, in on_api
    response = self.create_post_response(request, r)
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/wsgi.py", line 276, in create_post_response
    buff = json.dumps(result, default=json_defaul_handler)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected

```
The DATA is UTF8, sent to email

D.

**Comment by platipusica** [comment]
Export:

[test_1.0.0_5.4.96_2020-07-28_15-02-23.zip](https://github.com/jam-py/jam-py/files/4986574/test_1.0.0_5.4.96_2020-07-28_15-02-23.zip)

**Comment by jam-py** [comment]
Hi,

This error is raised when the server sends data to the client,
it converts data to json and encounters some object that it doesn't know to
convert to json.
The import can not help, because it doesn't contain data.

Regards,
Andrew Yushev


вт, 28 июл. 2020 г. в 10:17, platipusica <notifications@github.com>:

**Comment by jam-py** [comment]
Can you send me the zip archive of the project to find the problem?

ср, 29 июл. 2020 г. в 11:01, Andrew Yushev <yushevaa@gmail.com>:

**Comment by platipusica** [comment]
Sent DB to email. Pls Import Employe table
Note, -1 for insurance I've set the TEXT, as well as dates fields. Same error.
