### ISSUE TITLE
dev v6 issue

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#180]
when tried to access sso.html or any file:
```
10.0.2.2 - - [08/Sep/2020 11:03:20] "POST /api HTTP/1.1" 200 -
10.0.2.2 - - [08/Sep/2020 11:03:33] "GET /sso.html HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/wsgi.py", line 228, in __call__
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/third_party/werkzeug/local.py", line 230, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/third_party/werkzeug/middleware/shared_data.py", line 260, in __call__
    return self.app(environ, start_response)
  File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/wsgi.py", line 233, in __call__
    except HTTPException(e):
NameError: name 'e' is not defined
10.0.2.2 - - [08/Sep/2020 11:03:33] "GET /sso.html?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
10.0.2.2 - - [08/Sep/2020 11:03:33] "GET /sso.html?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
10.0.2.2 - - [08/Sep/2020 11:03:33] "GET /sso.html?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
10.0.2.2 - - [08/Sep/2020 11:03:33] "GET /sso.html?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
^C
```
(py36) root@venus:/var/www/demo# ls sso.html 
sso.html
(py36) root@venus:/var/www/demo# python --version
Python 3.6.8

This works in python --version
Python 3.5.2

**Comment by platipusica** [comment]
And:

```
(py36) root@venus:/var/www/demo2# ./server.py 
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET / HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/css/bootstrap-cerulean.css HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/css/datepicker.css HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/css/bootstrap-modal.css HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/css/bootstrap-responsive.css HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/css/jam.css HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /css/project.css HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/js/jquery.js HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/js/bootstrap.js HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/js/bootstrap-modal.js HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/js/bootstrap-modalmanager.js HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/js/jquery.maskedinput.js HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/js/bootstrap-datepicker.js HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/js/jam.js HTTP/1.1" 304 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "POST /api HTTP/1.1" 200 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /js/demo.js HTTP/1.1" 200 -
10.0.2.2 - - [08/Sep/2020 13:04:03] "GET /jam/img/glyphicons-halflings.png HTTP/1.1" 304 -
ERROR - malformed database schema (DEMO_INVOICE_TABLE_IDX) - table DEMO_INVOICE_TABLE has no column named None:
SELECT "DEMO_INVOICES"."CUSTOMER", "DEMO_INVOICES"."INVOICE_DATE", "DEMO_INVOICES"."SUBTOTAL", "DEMO_INVOICES"."TAXRATE", "DEMO_INVOICES"."TAX", "DEMO_INVOICES"."TOTAL", "DEMO_INVOICES"."ID", "DEMO_INVOICES"."DELETED", "DEMO_INVOICES"."PAID", "DEMO_INVOICES"."RECORD_VERSION", DEMO_CUSTOMERS_34."LASTNAME" AS CUSTOMER_LOOKUP, DEMO_CUSTOMERS_34."FIRSTNAME" AS FIRSTNAME_LOOKUP, DEMO_CUSTOMERS_34."ADDRESS" AS BILLING_ADDRESS_LOOKUP, DEMO_CUSTOMERS_34."CITY" AS BILLING_CITY_LOOKUP, DEMO_CUSTOMERS_34."COUNTRY" AS BILLING_COUNTRY_LOOKUP, DEMO_CUSTOMERS_34."POSTALCODE" AS BILLING_POSTAL_CODE_LOOKUP, DEMO_CUSTOMERS_34."STATE" AS BILLING_STATE_LOOKUP FROM "DEMO_INVOICES" AS "DEMO_INVOICES" LEFT OUTER JOIN "DEMO_CUSTOMERS" AS DEMO_CUSTOMERS_34 ON "DEMO_INVOICES"."CUSTOMER" = DEMO_CUSTOMERS_34."ID" WHERE "DEMO_INVOICES"."DELETED"=0 ORDER BY "DEMO_INVOICES"."INVOICE_DATE" DESC LIMIT 0, 4
Traceback (most recent call last):
  File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/items.py", line 154, in __execute_select
    cursor.execute(sql)
sqlite3.DatabaseError: malformed database schema (DEMO_INVOICE_TABLE_IDX) - table DEMO_INVOICE_TABLE has no column named None
10.0.2.2 - - [08/Sep/2020 13:04:03] "POST /api HTTP/1.1" 200 -
10.0.2.2 - - [08/Sep/2020 13:04:30] "GET /register.html HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/wsgi.py", line 228, in __call__
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/third_party/werkzeug/local.py", line 230, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/third_party/werkzeug/middleware/shared_data.py", line 260, in __call__
    return self.app(environ, start_response)
  File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/wsgi.py", line 233, in __call__
    except HTTPException(e):
NameError: name 'e' is not defined
```

**Comment by jam-py** [comment]
Thank you for your feedback!
Fixed the bug.

вт, 8 сент. 2020 г. в 08:07, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Still the same:

```
127.0.0.1 - - [09/Sep/2020 13:32:11] "GET /register.html HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/share/py37/lib/python3.7/site-packages/jam.py-6.0.20-py3.7.egg/jam/third_party/werkzeug/local.py", line 230, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/usr/local/share/py37/lib/python3.7/site-packages/jam.py-6.0.20-py3.7.egg/jam/third_party/werkzeug/wsgi.py", line 489, in __init__
    iterator = iter(iterable)
TypeError: 'NotFound' object is not iterable
127.0.0.1 - - [09/Sep/2020 13:32:11] "GET /register.html?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [09/Sep/2020 13:32:11] "GET /register.html?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Sep/2020 13:32:11] "GET /register.html?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Sep/2020 13:32:12] "GET /register.html?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by jam-py** [comment]
You are using register.html.
I'll check that.

ср, 9 сент. 2020 г. в 08:34, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Not only register.html, any file!
