### ISSUE TITLE
dev v6 Apache issue

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#182]
```
[Tue Sep 08 11:20:40.330506 2020] [mpm_event:notice] [pid 3882:tid 140674386954112] AH00491: caught SIGTERM, shutting down
[Tue Sep 08 11:20:41.127662 2020] [mpm_event:notice] [pid 4004:tid 140217928206208] AH00489: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f mod_wsgi/4.7.1 Python/3.6 configured -- resuming normal operations
[Tue Sep 08 11:20:41.127734 2020] [core:notice] [pid 4004:tid 140217928206208] AH00094: Command line: '/usr/sbin/apache2'
[Tue Sep 08 11:20:46.777899 2020] [wsgi:error] [pid 4008:tid 140217753220864] [client 10.0.2.2:44982] /var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/third_party/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
[Tue Sep 08 11:20:46.777979 2020] [wsgi:error] [pid 4008:tid 140217753220864] [client 10.0.2.2:44982]   BrokenFilesystemWarning,
[Tue Sep 08 11:20:46.798804 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982] mod_wsgi (pid=4008): Exception occurred processing WSGI script '/var/www/demo/wsgi.py'., referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800239 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982] Traceback (most recent call last):, referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800305 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982]   File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/wsgi.py", line 228, in __call__, referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800315 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982]     raise NotFound(), referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800526 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982] werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again., referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800559 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982] , referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800567 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982] During handling of the above exception, another exception occurred:, referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800571 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982] , referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800581 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982] Traceback (most recent call last):, referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800781 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982]   File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/third_party/werkzeug/local.py", line 230, in application, referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800800 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982]     return ClosingIterator(app(environ, start_response), self.cleanup), referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800815 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982]   File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/third_party/werkzeug/middleware/shared_data.py", line 260, in __call__, referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800822 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982]     return self.app(environ, start_response), referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.800831 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982]   File "/var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/wsgi.py", line 233, in __call__, referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.801015 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982]     except HTTPException(e):, referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:46.801045 2020] [wsgi:error] [pid 4008:tid 140217744828160] [client 10.0.2.2:44982] NameError: name 'e' is not defined, referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:47.869988 2020] [wsgi:error] [pid 4009:tid 140217478518528] [client 10.0.2.2:44992] /var/www/demo/py36/lib/python3.6/site-packages/jam.py-6.0.19-py3.6.egg/jam/third_party/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii', referer: https://sso.localhost:4443/demo/
[Tue Sep 08 11:20:47.870904 2020] [wsgi:error] [pid 4009:tid 140217478518528] [client 10.0.2.2:44992]   BrokenFilesystemWarning,, referer: https://sso.localhost:4443/demo/
```

This worked before with jam 5.x

**Comment by platipusica** [comment]
And with Py3.7:

```
[Tue Sep 08 12:43:38.938859 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930]   File "/usr/local/share/py37/lib/python3.7/site-packages/jam.py-6.0.19-py3.7.egg/jam/admin/builder.py", line 124, in on_created
[Tue Sep 08 12:43:38.938864 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930]     init_task_attr(task)
[Tue Sep 08 12:43:38.938870 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930]   File "/usr/local/share/py37/lib/python3.7/site-packages/jam.py-6.0.19-py3.7.egg/jam/admin/builder.py", line 103, in init_task_attr
[Tue Sep 08 12:43:38.938875 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930]     task.task_db_module = get_database(task.app, task.task_db_type, task.task_db_info.lib)
[Tue Sep 08 12:43:38.938881 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930]   File "/usr/local/share/py37/lib/python3.7/site-packages/jam.py-6.0.19-py3.7.egg/jam/db/databases.py", line 9, in get_database
[Tue Sep 08 12:43:38.938886 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930]     from .postgres_db import db
[Tue Sep 08 12:43:38.938905 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930]   File "/usr/local/share/py37/lib/python3.7/site-packages/jam.py-6.0.19-py3.7.egg/jam/db/postgres_db.py", line 83
[Tue Sep 08 12:43:38.938914 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930]     print sql
[Tue Sep 08 12:43:38.938931 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930]             ^
[Tue Sep 08 12:43:38.938940 2020] [wsgi:error] [pid 9160] [remote 127.0.0.1:47930] SyntaxError: Missing parentheses in call to 'print'. Did you mean print(sql)?
```

**Comment by jam-py** [comment]
Thank you for your feedback!
Fixed the bug.

вт, 8 сент. 2020 г. в 07:48, platipusica <notifications@github.com>:
