### ISSUE TITLE
Edit Lock traceback

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#186]
HI, 

not sure if this is error though:

```
ERROR - Saving is forbidden. This record has been changed by another user since you started editing it
Traceback (most recent call last):
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.20-py3.8.egg/jam/wsgi.py", line 638, in on_api
    data = self.get_response(item, method, params)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.20-py3.8.egg/jam/wsgi.py", line 663, in get_response
    return item.apply_changes(params, safe=True)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.20-py3.8.egg/jam/items.py", line 271, in apply_changes
    result = self.apply_delta(delta, params, con)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.20-py3.8.egg/jam/items.py", line 245, in apply_delta
    return db.process_changes(delta, connection, params)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.20-py3.8.egg/jam/db/db.py", line 362, in process_changes
    self.process_records(delta, connection, cursor, safe, changes)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.20-py3.8.egg/jam/db/db.py", line 346, in process_records
    self.process_record(it, connection, cursor, safe, changes, details)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.20-py3.8.egg/jam/db/db.py", line 330, in process_record
    self.update_record(delta, cursor, changes, details_changes)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.20-py3.8.egg/jam/db/db.py", line 204, in update_record
    raise Exception(consts.language('edit_record_modified'))
Exception: Saving is forbidden. This record has been changed by another user since you started editing it

```

**Comment by jam-py** [comment]
Thank you for the feedback.
I fixed this bug in the latest version.
Please check.

чт, 17 сент. 2020 г. в 08:34, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Not quite sure what's going on:
```
HEAD is now at cd8d371 Detected bugs fixed
(py38May) dbabic@venus ~/Downloads/jam-py-develop $ git pull 
Updating cd8d371..5637a82
Fast-forward
 builder/admin.sqlite       | Bin 498688 -> 498688 bytes
 builder/builder.sqlite     | Bin 106496 -> 106496 bytes
 builder/js/app_builder.js  |  49 +++++++++++++++++++++++++-----------------
 demo/admin.sqlite          | Bin 102400 -> 103424 bytes
 demo/demo.sqlite           | Bin 1340416 -> 1340416 bytes
 demo/index.html            | 142 -------------------------------------------------------------------------------------------------------------------------
 demo/js/demo.js            |  16 ++++++++------
 jam/__init__.py            |   2 +-
 jam/admin/builder.py       |   2 +-
 jam/admin/upgrade.py       |  32 ++++++++++++++++++++++++++--
 jam/db/db.py               |   2 +-
 jam/items.py               |   8 +++----
 jam/js/admin.js            |  57 ++++++++++++++++++++++++++++---------------------
 jam/js/admin.min.js        |  16 +++++++-------
 jam/js/jam.js              |  89 ++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------
 jam/js/jam.min.js          |  34 ++++++++++++++++-------------
 jam/project/admin.sqlite   | Bin 80896 -> 80896 bytes
 jam/project/index.html     | 123 --------------------------------------------------------------------------------------------------------
 jam/project/templates.html | 118 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 jam/tree.py                |   2 +-
 jam/wsgi.py                |  66 +++++++++++++++++++++++++++++++++++++-------------------
 21 files changed, 358 insertions(+), 400 deletions(-)
 create mode 100644 jam/project/templates.html
```

This is not v6.024? Demo is in Safe mode, this is what I've got:

![Screenshot from 2020-09-16 09-35-08](https://user-images.githubusercontent.com/9026100/93540911-ae655880-f987-11ea-9f7b-7d7aaee7b5e6.png)

**Comment by platipusica** [comment]
Just checked, still the same:

```
ERROR - Saving is forbidden. This record has been changed by another user since you started editing it
Traceback (most recent call last):
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.24-py3.8.egg/jam/wsgi.py", line 660, in on_api
    data = self.get_response(item, method, params)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.24-py3.8.egg/jam/wsgi.py", line 685, in get_response
    return item.apply_changes(params, safe=True)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.24-py3.8.egg/jam/items.py", line 272, in apply_changes
    result = self.apply_delta(delta, params, con)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.24-py3.8.egg/jam/items.py", line 246, in apply_delta
    return db.process_changes(delta, connection, params)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.24-py3.8.egg/jam/db/db.py", line 362, in process_changes
    self.process_records(delta, connection, cursor, safe, changes)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.24-py3.8.egg/jam/db/db.py", line 346, in process_records
    self.process_record(it, connection, cursor, safe, changes, details)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.24-py3.8.egg/jam/db/db.py", line 330, in process_record
    self.update_record(delta, cursor, changes, details_changes)
  File "/home/Downloads/SAML/py38May/lib/python3.8/site-packages/jam.py-6.0.24-py3.8.egg/jam/db/db.py", line 204, in update_record
    raise Exception(consts.language('edit_record_modified'))
Exception: Saving is forbidden. This record has been changed by another user since you started editing it
```

**Comment by jam-py** [comment]
Hi,

I can not reproduce this error.
Can you explain what you are doing?

пт, 18 сент. 2020 г. в 06:04, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Hi Andrey, 

same as before, updating same Customers record from 2 Browsers at the same time....

**Comment by platipusica** [comment]
Did you update DEV branch?

**Comment by platipusica** [comment]
Steps:

 2045  git clone -b develop https://github.com/jam-py/jam-py.git jam-py-develop
 2046  cd jam-py-develop
 2047  python setup.py install
 2048  cd demo/
 2049  ./server.py

**Comment by jam-py** [comment]
Dean, due to your help I found some problem with the locking.
I need some time to solve it.
Thank you!


пт, 18 сент. 2020 г. в 10:38, platipusica <notifications@github.com>:
