### ISSUE TITLE
Reports on ver 4.0.48

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#19]
Hi Andrew

thanks for sorting the wsgi problems, looks great now.

I noticed the reports are not working well on this version. Have a look at jam.is.uwa.edu.au, created the Invoice today (2017/01/12) and can't set the filter to display it or Report to print it (Customer Purchases, set the Date to 2017/01/12, and customer to Dean).

Looks like the Report is printing into ODS only, pdf, xls or html not working. Not a big deal, just noticing.

Cheers

Dean

**Comment by dbabicwa** [comment]
Hold on, still configuring apache, will report soon...

**Comment by dbabicwa** [comment]
Confirmed.
The site is now running with ssl as well: https://jam.research.uwa.edu.au/

**Comment by jam-py** [comment]
Hi, Dean

I've tried to print a report. It printed it and returned as ods file. To
convert a report to pdf the openoffice (libreoffice) must be installed on
the server.

Andrew



2017-01-12 8:54 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by jam-py** [comment]
Yes there is a problem with reports. Will check and write later

2017-01-12 16:24 GMT+03:00 Andrew Yushev <yushevaa@gmail.com>:

**Comment by dbabicwa** [comment]
I just found a problem with UTF8:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.48-py2.7.egg/jam/dataset.py", line 325, in get_lookup_text
    result = unicode(result)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.48-py2.7.egg/jam/wsgi.py", line 278, in on_api
    data = self.get_response(item, method, params)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.48-py2.7.egg/jam/wsgi.py", line 305, in get_response
    return item.print_report(*params), ''
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.48-py2.7.egg/jam/server_classes.py", line 386, in print_report
    return copy_report.generate(param_values, url, ext)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.48-py2.7.egg/jam/server_classes.py", line 422, in generate
    self.on_generate(self)
  File "demo.reports.invoice", line 8, in on_generate
    customer = invoices.firstname.display_text + ' ' + invoices.customer.display_text
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)
127.0.0.1 - - [13/Jan/2017 21:46:03] "POST /api HTTP/1.1" 200 -

**Comment by jam-py** [comment]
Hi Dean.
I have not solved the problems yet. First it was an urgent work and then I
got ill.
I will do it a bit later
Andrew


2017-01-13 16:47 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Don't worry about it, and get well !
