### ISSUE TITLE
better handling 404 error

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#193]
Hi 
if I may suggests, Jam should handle better 4040 error like this one:

```
ERROR - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/.../jam.py-5.4.93/auth/jam/wsgi.py", line 265, in __call__
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
127.0.0.1 - - [09/Nov/2020 15:01:12] "GET /sdafsdfg HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/.../jam.py-5.4.93/auth/jam/third_party/werkzeug/local.py", line 230, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/.../jam.py-5.4.93/auth/jam/third_party/werkzeug/wsgi.py", line 489, in __init__
    iterator = iter(iterable)
TypeError: 'NotFound' object is not iterable
```

Basically anything added after "/" like "sdafsdfg" would produce 404 on dev server, and on Apache 500 error.
Cheers

**Comment by platipusica** [comment]
Something like this as solution?
https://www.geeksforgeeks.org/python-404-error-handling-in-flask/

**Comment by platipusica** [comment]
Cheers! I see this in v6 and Apache:
"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."
