### ISSUE TITLE
V7 BUG on demo project: btn set media type in Track view form

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#233]
On Demo procjet, I'm trying to update media type in Tracks view form but there is error in console log:

Uncaught TypeError: this.master.field_by_name(...) is undefined  [item.js:1679:62](http://localhost:8080/jam/js/modules/item.js)

Also, there is no item.alert message in browser...

Danijel

**Comment by jam-py** [comment]
Fixed the bug

ср, 15 мар. 2023 г. в 19:36, crni_kaurin ***@***.***>:

**Comment by crnikaurin** [comment]
Hi Andrew. On V 7.0.6 there is error again:

ERROR - 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\wsgi.py", line 695, in on_api
    data = self.get_response(item, method, params)
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\wsgi.py", line 722, in get_response
    return self.server_func(item, params[0], params[1])
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\wsgi.py", line 733, in server_func
    result = func(obj, *params)
  File "demo.catalogs.tracks", line 10, in set_media_type
    c.apply()
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\dataset.py", line 1811, in apply
    self.do_apply({id_str: params}, safe, connection)
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\items.py", line 111, in do_apply
    data, error = self.apply_changes((changes, params), safe, connection)
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\items.py", line 264, in apply_changes
    result = self.apply_delta(delta, params_dict, con)
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\items.py", line 236, in apply_delta
    db.process_changes(delta, connection, params)
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\db\db.py", line 390, in process_changes
    self.process_records(delta, connection, cursor, params, safe)
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\db\db.py", line 378, in process_records
    self.process_record(d, connection, cursor, safe)
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\db\db.py", line 340, in process_record
    self.update_record(delta, cursor)
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\db\db.py", line 178, in update_record
    self.check_record_version(delta, cursor)
  File "C:\Users\W10\AppData\Local\Programs\Python\Python310\lib\site-packages\jam.py-7.0.6-py3.10.egg\jam\db\db.py", line 168, in check_record_version
    if delta._record_version_field.value != delta._record_version_field.cur_value:
AttributeError: 'NoneType' object has no attribute 'value'
127.0.0.1 - - [22/Mar/2023 10:26:35] "POST /api HTTP/1.1" 200 -

**Comment by jam-py** [comment]
Thank you! I fixed it.
ср, 22 мар. 2023 г. в 12:28, crni_kaurin ***@***.***>:
