### ISSUE TITLE
V7 BUG: trying to run existing project - "task is not defined"

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#234]
Hi.

I'm trying to run existing project and after login, page won't load and there is error in console:

Uncaught ReferenceError: task is not defined
    <anonymous> http://localhost:8080/:1575
    jQuery 13
[localhost:8080:1575:17](http://localhost:8080/)
    <anonymous> http://localhost:8080/:1575
    jQuery 13

reffers to this code in index.html:

<script>
            $(document).ready(function(){
                task.load();
              });
</script>

Danijel

**Comment by crnikaurin** [comment]
When removed this code from index.htm:
<script> $(document).ready(function(){ task.load(); }); </script>

there is another error in console:

"Uncaught SyntaxError: import declarations may only appear at top level of a module"

reffering to this code: [jam.js:3](http://localhost:8080/jam/js/jam.js)

...
use strict";

import Task from "./modules/task.js";

(function($) {

    $.event.special.destroyed = {
        remove: function(o) {
            if (o.handler) {
                o.handler();
            }
        }
    };

    window.task = new Task();

})(jQuery);

**Comment by platipusica** [comment]
Andrew, are we sure abut that advice? I just did this:
 2027  cd ../../jam.py-5.4.119/demo
 2028  mv index.html index.html_orig_v5
 2029  cp ~/Downloads/jam.py-7.0.3/demo/index.html .
 2030  ll ~/Downloads/jam.py-7.0.3/demo
 2031  cp ~/Downloads/jam.py-7.0.3/demo/templates.html .
 2032  ll
 2033  ./server.py 

and getting:
```
~/Downloads/jam.py-5.4.119/demo$ ./server.py 
Traceback (most recent call last):
  File "./server.py", line 7, in <module>
    application = create_application(__file__)
  File "/home/dbabic/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/wsgi.py", line 103, in create_application
    application = App(work_dir, load_task)
  File "/home/dbabic/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/wsgi.py", line 165, in __init__
    create_admin(self)
  File "/home/dbabic/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/admin/admin.py", line 69, in create_admin
    init_admin(task)
  File "/home/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/admin/admin.py", line 59, in init_admin
    version7_upgrade(task)
  File "/home/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/admin/upgrade.py", line 203, in version7_upgrade
    field.post()
  File "/home/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/dataset.py", line 1663, in post
    raise DatasetInvalidState(consts.language('not_edit_insert_state') % self.item_name)
jam.dataset.DatasetInvalidState: Item sys_fields is not in edit or insert state
```
