### ISSUE TITLE
V7: Import metadata does not work

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#237]
Using v7 Demo Export and import into MSSQL

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.0.2.15:8080
Press CTRL+C to quit
127.0.0.1 - - [21/Mar/2023 13:22:41] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [21/Mar/2023 13:23:00] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [21/Mar/2023 13:23:00] "POST /api HTTP/1.1" 200 -
INFO - Import: reading data
INFO - Import: checking data integrity
INFO - Import: analyzing changes
ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/admin/import_metadata.py", line 240, in analize_data
    delta = self.get_delta('sys_indices', options=['delete'])
  File "/home/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/admin/import_metadata.py", line 402, in get_delta
    return item.delta()
  File "/home/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/dataset.py", line 1878, in delta
    result.change_log.set_changes(changes)
  File "/home/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/dataset.py", line 808, in set_changes
    self.fields = changes['fields']
TypeError: 'NoneType' object is not subscriptable
INFO - The metadata have not been imported
INFO - Import: deleteing tmp files <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<  deleteing has typo in it.....

**Comment by platipusica** [comment]
Even the simple new project with one table, export/import does not work. Same TypeError

**Comment by jam-py** [comment]
Thank you! I'll check it out tomorrow.

вт, 21 мар. 2023 г. в 09:16, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Important to note this issue for mailgroup readers:

https://github.com/jam-py/jam-py/issues/238

**Comment by platipusica** [comment]
Hi,
can we put some urgency in that since no DB testing can be done?
And pls remember INFO - Import: deleteing <--- this is typo, it is deleting.

**Comment by crnikaurin** [comment]
@platipusica try this now with new package
