### ISSUE TITLE
V7: touch builder.html still showing builder

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#238]
Hence 
I can't use:
touch builder.html
to restrict access to builder.

**Comment by platipusica** [comment]
Plus, click on Production breaks access:
ERROR - a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/home/dbabic/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/wsgi.py", line 695, in on_api
    data = self.get_response(item, method, params)
  File "/home/dbabic/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/wsgi.py", line 722, in get_response
    return self.server_func(item, params[0], params[1])
  File "/home/dbabic/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/wsgi.py", line 733, in server_func
    result = func(obj, *params)
  File "/home/dbabic/Downloads/SAML/py38v6/lib/python3.8/site-packages/jam/admin/builder.py", line 173, in server_set_production
    f.write(text)
TypeError: a bytes-like object is required, not 'str'
