### ISSUE TITLE
MSSQL and MYSQL issue

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#250]
Hi Andrew,
looks like a simple SQL does not work with MSSQL 2019, ie:
```
def get_records(item):
    res, inventory = [], product = [], ''

    product = item.task.products.copy()
    product.set_where(id=41)
    product.open(fields=['id', 'product_name', 'target_level'], 
        group_by=['id'], order_by=['id'])
.
.
```
Log file:
```
ERROR - (8120, b"Column 'PRODUCTS.PRODUCT_NAME' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 459, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (8120, b"Column 'PRODUCTS.PRODUCT_NAME' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dbabic/Downloads/SAML/py38/lib/python3.8/site-packages/jam/execute.py", line 15, in execute_select
    cursor.execute(command)
  File "src/pymssql/_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute
```

The data will load into MSSQL with no issues:
``` * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO - copying started
INFO - copying started
INFO - copying droping indexes
INFO - copying table suppliers records: 11
INFO - copying table products records: 46
INFO - copying table customers records: 30
INFO - copying table employees records: 10
INFO - copying table shippers records: 4
INFO - copying table orders records: 49
INFO - copying table invoices records: 35
INFO - copying table order_details_status records: 6
INFO - copying table orders_status records: 4
INFO - copying table orders_tax_status records: 2
INFO - copying table purchase_order_status records: 4
INFO - copying table inventory_transactions records: 102
INFO - copying table inventory_transaction_types records: 4
INFO - copying table purchase_orders records: 29
INFO - copying table order_details records: 58
INFO - copying table purchase_order_details records: 56
INFO - copying restoring indexes
INFO - copying finished
```

Thoughts?

PS
Please observe :INFO - copying droping indexes
This is a typo, the word is dropping.

[northwind.sqlite3.zip](https://github.com/jam-py/jam-py/files/11195495/northwind.sqlite3.zip)

**Comment by platipusica** [comment]
**By the look, none of group_by and order_by are working.**

Also, the SAME sqlite3 from above will load data to MSSQL, but it will fail with MYSQL. This is due to ID with MYSQL:

ERROR - (1062, "Duplicate entry '1' for key 'orders_status.PRIMARY'")
ERROR - (1062, "Duplicate entry '1' for key 'order_details_status.PRIMARY'")
ERROR - (1062, "Duplicate entry '1' for key 'orders_tax_status.PRIMARY'")
ERROR - (1062, "Duplicate entry '1' for key 'purchase_order_status.PRIMARY'")
ie:
MySQLdb.IntegrityError: (1062, "Duplicate entry '1' for key 'orders_tax_status.PRIMARY'")

etc...

Logically there is no explanation why MSSQL would work and MYSQL would not.
And vice versa, why would
```
def get_records(item):
```
work with MYSQL and fail with MSSQL. 

Regards

**Comment by platipusica** [comment]
Postgresql work perfectly! Same database from above imported with:

```
def on_created(task):
    task.copy_database(SQLITE, 'northwind.sqlite3')
```

```
cat /var/log/postgresql/postgresql-12-main.log
2023-04-11 12:10:11.019 AWST [9637] LOG:  starting PostgreSQL 12.14 (Ubuntu 12.14-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
2023-04-11 12:10:11.020 AWST [9637] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-04-11 12:10:11.020 AWST [9637] LOG:  listening on IPv4 address "127.0.1.1", port 5432
```

**Comment by jam-py** [comment]
Hi, Drazen

Try to add product_name to group_by field list

Regards,
Andrew

вт, 11 апр. 2023 г., 05:55 platipusica ***@***.***>:

**Comment by platipusica** [comment]
Thanks,

good to known that group_by needs all fields for MSSQL.
Regarding data load, this is now also working with MYSQL.

Please do not forget this:
```
Please observe :INFO - copying droping indexes
```
This is a typo, the word is dropping.
