### ISSUE TITLE
jammy jellyfish ubuntu Apache and Jam broken

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#260]
Hi Andrew,

looks like Apache2 does not work with Jam.

Please follow the discussion from here:
https://github.com/GrahamDumpleton/mod_wsgi/issues/817

simple install:
```
 apt install python3-virtualenv
 virtualenv -p python3 venv
 source venv/bin/activate
pip install mod_wsgi 
mod_wsgi-express module-config
pip install jam.py
```
Update or create files for Jam App:
```
vi /etc/apache2/mods-enabled/wsgi.load
#LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so
LoadModule wsgi_module "/var/www/html/jam/venv/lib/python3.10/site-packages/mod_wsgi/server/mod_wsgi-py310.cpython-310-x86_64-linux-gnu.so"
```

create jam.conf for Apache and activate jam
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/jam
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        LogLevel trace5
        WSGIDaemonProcess web python-home=/var/www/html/jam/venv python-path=/var/www/html/jam/venv/lib/python3.10/site-packages user=www-data group=www-data processes=1 threads=5
        WSGIProcessGroup web
    WSGIScriptAlias / /var/www/html/jam/wsgi.py
        <Directory /var/www/html/jam>
        Options +ExecCGI
        SetHandler wsgi-script
        AddHandler wsgi-script .py
        Require all granted
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>
    <Directory /var/www/html/jam/static>
        Require all granted
    </Directory>
</VirtualHost>
```

Apache is working with a simple wsgi app, for example any of this (replaced wsgi.py content with below examples):

https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#python-installation-in-use
![Screenshot from 2023-05-31 10-40-06](https://github.com/jam-py/jam-py/assets/9026100/b879ee87-3aee-465a-81ff-29bd3c837bf2)

This is from the VirtualBox, you can use:
curl http://127.0.0.1/wsgi.py

But not with Jam.

**Comment by platipusica** [comment]
Hi, 
IMO, not Apache issue since gunicorn does not work either when used with virtualenv :
```
(venv) $gunicorn wsgi
[2023-05-31 07:54:55 +0000] [2615] [INFO] Starting gunicorn 20.1.0
[2023-05-31 07:54:55 +0000] [2615] [INFO] Listening at: http://127.0.0.1:8000/ (2615)
[2023-05-31 07:54:55 +0000] [2615] [INFO] Using worker: sync
[2023-05-31 07:54:55 +0000] [2616] [INFO] Booting worker with pid: 2616
[2023-05-31 07:54:55 +0000] [2616] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/html/jam/wsgi.py", line 2, in <module>
    from jam.wsgi import create_application
ModuleNotFoundError: No module named 'jam'
[2023-05-31 07:54:55 +0000] [2616] [INFO] Worker exiting (pid: 2616)
[2023-05-31 07:54:55 +0000] [2615] [INFO] Shutting down: Master
[2023-05-31 07:54:55 +0000] [2615] [INFO] Reason: Worker failed to boot.
(venv) $pip list |grep jam
jam.py       5.4.130
```

**Comment by jam-py** [comment]
Hi, Drazen

I am by no means an Apache expert.
But, as I understand, this problem is for any Python framework, Django,
Flask and so on.
Thank you for following that. Please keep us here informed.

Regards,
Andrew


ср, 31 мая 2023 г. в 11:06, platipusica ***@***.***>:

**Comment by platipusica** [comment]
They changed the Apache2 behavior.

it needs:
WSGIApplicationGroup %{GLOBAL}


So config looks like this:
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/jam
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        LogLevel trace5
        WSGIDaemonProcess web python-home=/var/www/html/jam/venv python-path=/var/www/html/jam/venv/lib/python3.10/site-packages user=www-data group=www-data processes=1 threads=5
        WSGIProcessGroup web
        WSGIApplicationGroup %{GLOBAL}
    WSGIScriptAlias / /var/www/html/jam/wsgi.py
        <Directory /var/www/html/jam>
        Options +ExecCGI
        SetHandler wsgi-script
        AddHandler wsgi-script .py
        Require all granted
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>
    <Directory /var/www/html/jam/static>
        Require all granted
    </Directory>
</VirtualHost>
```
