### ISSUE TITLE
Apple Mac, project import does not work

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#309]
Hi, 

```
INFO - Import: reading data
ERROR - [Errno 2] No such file or directory: '/var/folders/w6/d1tmy0s55tb4k0rdnh74jrww0000gn/T/tmpvupsah8w/task.dat'
Traceback (most recent call last):
  File "/Users/user1/Downloads/py3.9v5/lib/python3.9/site-packages/jam/admin/import_metadata.py", line 117, in prepare_data
    data = file_read(file_name)
  File "/Users/user1/Downloads/py3.9v5/lib/python3.9/site-packages/jam/common.py", line 439, in file_read
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/w6/d1tmy0s55tb4k0rdnh74jrww0000gn/T/tmpvupsah8w/task.dat'
INFO - The metadata have not been imported
INFO - Import: deleteing tmp files
```

Also, **deleteing** has typo.

**Comment by platipusica** [comment]
```
(py3.9v5) users-MacBook-Pro:test user1$ python --version
Python 3.9.6
```
Checked v4, all good on Mac. This is how I tested it years ago with v4.

![Screenshot 2024-04-06 at 11 00 47 am](https://github.com/jam-py/jam-py/assets/9026100/6e1d52e7-ff59-4a05-9fe6-48b798ef4963)

**Comment by platipusica** [comment]
This code is working from v4:
```
/Users/user1/Downloads/py3.9v5/lib/python3.9/site-packages/jam/admin/import_metadata.py

def prepare_data(self):
    if self.success:
        self.show_progress(self.task.language('import_reading_data'))
        try:
            self.tmpdir = os.path.join(os.getcwd(), 'tmp-' + datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S"))
```

![Screenshot 2024-04-06 at 8 48 01 pm](https://github.com/jam-py/jam-py/assets/9026100/8bfcb32d-965b-4db5-bb97-d1280bfcb85d)
