### ISSUE TITLE
V7, copy_db issue

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#317]
Hi, 
if this is the correct code, then it is failing:
```
from jam.db import sqlite_db
def copy_db(task):
    task.copy_database(sqlite_db, 'demo.sqlite')
def on_created(task):
  copy_db(task)
```

with:
```
127.0.0.1 - - [12/Apr/2024 04:08:50] "POST /api HTTP/1.1" 200 -
record_version
deleted
INFO - copying started
INFO - copying started
INFO - copying droping indexes
ERROR - 'NoneType' object has no attribute 'get_record_count_query'
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.10/site-packages/jam/admin/copy_db.py", line 155, in copy_database
    record_count = count_records(item, db, connection)
  File "/home/mint/.local/lib/python3.10/site-packages/jam/admin/copy_db.py", line 130, in count_records
    sql, params = db.get_record_count_query(item, QueryData(params))
AttributeError: 'NoneType' object has no attribute 'get_record_count_query'
INFO - copying restoring indexes

127.0.0.1 - - [12/Apr/2024 04:10:07] "POST /api HTTP/1.1" 200 -
```

Thanks and I think that's enough issues from me :)

**Comment by platipusica** [comment]
```
from jam.db import sqlite_db
import sqlite3
def copy_db(task):
    print('DB Init')
    task.copy_database(sqlite_db, 'demo.sqlite')
def on_created(task):
  copy_db(task)
```

Fixed in jam-py-v5

**Comment by platipusica** [comment]
Postgres and mssql not working.
