### ISSUE TITLE
Opening files in text mode causes encoding error in non-Latin (and non-Russian) locales.

### ISSUE THREAD

**Issue by gschizas** [jam-py/jam-py#50]
See [adm_server.py, line 1125](https://github.com/jam-py/jam-py/blob/ef0c1d335d843aae2fd25b226bbc2cb63b454a38/jam/adm_server.py#L1125) and [adm_server.py, lines 2099-2100](https://github.com/jam-py/jam-py/blob/ef0c1d335d843aae2fd25b226bbc2cb63b454a38/jam/adm_server.py#L2099-L2100)

The first chunk should be replaced with 
```Python
    with open(file_name, 'rb') as f:
```
and the second one with
```Python
        with open(file_path, 'rb') as f:
            result['doc'] = to_unicode(f.read(), 'utf-8')
```

To reproduce the first part:

1. Needs Windows (my test was with Windows 10, but this probably is the same regardless of version) with any non-Latin (and probably not Russian) regional options. I used Greek.
2. Start a new project (go to an empty folder and enter `jam-project`, then `py server.py`)
3. Open http://localhost:8080/admin.html, select "English" and press Ok.
4. The following exception appears.

```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\jam\wsgi.py", line 376, in on_api
    data = self.get_response(item, method, params)
  File "C:\Program Files\Python36\lib\site-packages\jam\wsgi.py", line 405, in get_response
    return self.server_func(item, params[0], params[1])
  File "C:\Program Files\Python36\lib\site-packages\jam\wsgi.py", line 418, in server_func
    result = func(obj, *params)
  File "C:\Program Files\Python36\lib\site-packages\jam\adm_server.py", line 1126, in server_set_project_langage
    data = to_unicode(f.read(), 'utf-8')
  File "C:\Program Files\Python36\lib\encodings\cp1253.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8c in position 10443: character maps to <undefined>
```

To reproduce the second part:

1. After creating the application (entering name, database etc.) go to http://localhost:8080/admin.html
2. Go to Project ➡ Task and select the first Task (with ID 1)
3. Click on the "index.html" button
4. The following exception appears:

```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\jam\wsgi.py", line 376, in on_api
    data = self.get_response(item, method, params)
  File "C:\Program Files\Python36\lib\site-packages\jam\wsgi.py", line 405, in get_response
    return self.server_func(item, params[0], params[1])
  File "C:\Program Files\Python36\lib\site-packages\jam\wsgi.py", line 418, in server_func
    result = func(obj, *params)
  File "C:\Program Files\Python36\lib\site-packages\jam\adm_server.py", line 2100, in server_file_info
    result['doc'] = f.read()
  File "C:\Program Files\Python36\lib\encodings\cp1253.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8c in position 10443: character maps to <undefined>
```

**Comment by jam-py** [comment]
Thank you for opening an issue, 
I replaced russian words with english ones. 
I am sorry for the bug. 

Andrew Yushev
