### ISSUE TITLE
name 'buffer' is not defined

### ISSUE THREAD

**Issue by maxbry** [jam-py/jam-py#52]
I created a catalog, went to the user interfaces, added an entry. The entry appeared, but after reloading the page I'm getting `name 'buffer' is not defined`:

    Traceback (most recent call last):
      File "/home/ubuntu/jampy/lib/python3.5/site-packages/jam/wsgi.py", line 376, in on_api
        data = self.get_response(item, method, params)
      File "/home/ubuntu/jampy/lib/python3.5/site-packages/jam/wsgi.py", line 401, in get_response
        return item.select_records(params, safe=True)
      File "/home/ubuntu/jampy/lib/python3.5/site-packages/jam/server_classes.py", line 163, in select_records
        rows = self.task.execute_select(sqls[0])
      File "/home/ubuntu/jampy/lib/python3.5/site-packages/jam/server_classes.py", line 890, in execute_select
        raise Exception(error)

**Comment by jam-py** [comment]
Are you using PostgreSQL?

**Comment by jam-py** [comment]
The bug is fixed
