### ISSUE TITLE
Framework bugs with v5.1.1

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#58]
Looks like a bug:

~/Downloads/jam.py-5.1.1/demo $ ./server.py 8081
 * Running on http://0.0.0.0:8081/ (Press CTRL+C to quit)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-5.1.1-py2.7.egg/jam/adm_server.py", line 666, in delete_reports
    for f in os.listdir(path):

Cheers

D.

**Comment by dbabicwa** [comment]
Also, 

strange behavior when canceling a form, ie on
http://ms71.pro:1083/ 
Catalogs/Customers, select New, press immediately Tab to navigate to Last Name. press Escape!

It is picking up the data like pressed Edit.

D.

**Comment by jam-py** [comment]
I see the bugs. I will correct the code in the next release.
Thank you.
Andrew yushev
