### ISSUE TITLE
Python3 and mysql client (placeholder)

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#72]
Python 3:

```
pip install mysqlclient
Collecting mysqlclient
  Downloading https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 4.8MB/s 
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7c39xhsl/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-7c39xhsl/mysqlclient/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-7c39xhsl/mysqlclient/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
   
    ----------------------------------------
```

`sudo apt-get install libmysqlclient-dev`

```
pip install mysqlclient
.
Successfully installed mysqlclient-1.3.12

pip install fdb
.
Successfully installed fdb-2.0.0
```

**Comment by jam-py** [comment]
Thank you.

There was a bug with MySQL with Python 3 . I fixed it.
