### ISSUE TITLE
Import broken on py3, v5.4.4

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#75]
The App Import is broken if exported from 5.4.4 and import to 5.4.4.

I did import this app from v4.0.84

After import into 5.4.4 and sqlite, the app does not let me to change Jobs job_id. I suspect because it is PK and TEXT. 
But this is coming from Oracle HR schema, did not notice on time.

So I went to delete the jobs table and re-import, to make a new PK.

But, got this on table import:

sys_params error - f_theme: a value is required
Traceback (most recent call last):
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.5/site-packages/jam/wsgi.py", line 410, in on_api
    data = self.get_response(item, method, params)
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.5/site-packages/jam/wsgi.py", line 439, in get_response
    return self.server_func(item, params[0], params[1])
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.5/site-packages/jam/wsgi.py", line 452, in server_func
    result = func(obj, *params)
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.5/site-packages/jam/adm_server.py", line 2170, in get_fields_next_id
    params.post()
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.5/site-packages/jam/dataset.py", line 1884, in post
    self.check_record_valid()
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.5/site-packages/jam/dataset.py", line 1904, in check_record_valid
    field.check_valid()
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.5/site-packages/jam/dataset.py", line 476, in check_valid
    if self.check_reqired():
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.5/site-packages/jam/dataset.py", line 473, in check_reqired
    self.do_on_error(self.owner.task.language('value_required'))
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.5/site-packages/jam/dataset.py", line 503, in do_on_error
    raise TypeError(mess)
TypeError: a value is required

The zip is attached.

D.

[Ora_4.0.84_1.0.0_4.0.84_2018-05-21_16-20-59.zip](https://github.com/jam-py/jam-py/files/2021852/Ora_4.0.84_1.0.0_4.0.84_2018-05-21_16-20-59.zip)

**Comment by platipusica** [comment]
Hmm,

looks like this is ENV issue. Will need to look this in more details...
