### ISSUE TITLE
Export error using Portuguese pt-PT Language 

### ISSUE THREAD

**Issue by jptneumann** [jam-py/jam-py#76]
Hi!

I can´t export my project. The server show the follow error message:

```
/usr/lib/python2.7/genericpath.py:79: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  s1 = min(m)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jam/wsgi.py", line 410, in on_api
    data = self.get_response(item, method, params)
  File "/usr/local/lib/python2.7/dist-packages/jam/wsgi.py", line 439, in get_response
    return self.server_func(item, params[0], params[1])
  File "/usr/local/lib/python2.7/dist-packages/jam/wsgi.py", line 452, in server_func
    result = func(obj, *params)
  File "/usr/local/lib/python2.7/dist-packages/jam/adm_server.py", line 1114, in server_export_task
    common.zip_dir('js', zip_file)
  File "/usr/local/lib/python2.7/dist-packages/jam/common.py", line 471, in zip_dir
    arcname = os.path.relpath(os.path.join(dir, file_path))
  File "/usr/lib/python2.7/posixpath.py", line 434, in relpath
    i = len(commonprefix([start_list, path_list]))
  File "/usr/lib/python2.7/genericpath.py", line 79, in commonprefix
    s1 = min(m)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
```
I think that is caused by accents characters used in portuguese language. I´am using Jam.py Version 5.4.4.

**Comment by jam-py** [comment]
Hi,

I think this is because the path to your project contains non-ascii
characters.
I'll try to fix it.

Andrew Yushev

2018-06-11 10:23 GMT+03:00 platipusica <notifications@github.com>:

**Comment by jptneumann** [comment]
Hi Andrew!

You that's right. There was really a folder on the path with non-ascii
characters. I renamed and the export is working. Thanks for the tip!

@platipusica , thank you too!

**Comment by jam-py** [comment]
It is my pleasure, @jptneumann.
I fixed the bug
