### ISSUE TITLE
mysql disconnect

### ISSUE THREAD

**Issue by marcjammet** [jam-py/jam-py#89]
Hello,
jam.py 5.4.24 Python 2.7.8, mySQL 5.6
launch with 
```
python server.py 8081
```
I get an exception if I let the application run after about a day.
Any idea ? Other application using this same mysql does not get disconnected.
Thank you for your help

```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/opt/ActivePython-2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/ActivePython-2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ActivePython-2.7/lib/python2.7/site-packages/jam.py-5.4.24-py2.7.egg/jam/execute.py", line 234, in process_request
    db_host, db_port, db_encoding, con, command, params, call_proc, select)
  File "/opt/ActivePython-2.7/lib/python2.7/site-packages/jam.py-5.4.24-py2.7.egg/jam/execute.py", line 192, in execute_sql
    connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
```

**Comment by platipusica** [comment]
HI Marc

sorry for delay. I'll spin up mysql with your version and report back...

Cheers

**Comment by jam-py** [comment]
Hi, Marc

I fixed this issue.
Jam.py internally handles the connections to the database.
Whenever an exception is raised during execution of a request it recreates the connection.
It also recreates a connection after 1000 requests.
Now the connection is recreated after an hour of inactivity.

I'll post these changes to github tomorrow

Regards,
Andrew Yushev
